### PR TITLE
Copy the modules and unlock them

### PR DESCRIPTION
**Pull request by Jonne**
Hi, to be able to use composite DSC resources I had to copy them to the program files \ modules folder. This is the only way I could get it to work.

### CODE REVIEW

**Comment by Jonne** [comment]
Hi Matt, I added a sample DSC script with composite DSC resource.

**Comment by mefellows** [comment]
Thanks Jonne, this is much appreciated. I'll take a look at this over the next few days and run it by a few colleagues.

**Comment by mefellows** [comment]
Hi Jonne,

I have taken a look at this PR. Correct me if I'm wrong, but doesn't the current example already show the use of a Composite resource? The [SimpleWebsite](https://github.com/mefellows/vagrant-dsc/blob/master/development/modules/MyWebapp/DSCResources/SimpleWebsite/SimpleWebsite.schema.psm1) Configuration in the `MyWebApp` Module is a Composite resource used by the `MyWebsite.ps1` [manifest](https://github.com/mefellows/vagrant-dsc/blob/master/development/manifests/MyWebsite.ps1) in much the same way as the `CommonConfigModule.ps1` of your PR.

For me, I am able to `vagrant up` with this configuration with no problems. Are you using a different OS or WMF version? Perhaps the issue is portability across different Windows setups?

**Comment by Jonne** [comment]
You are right, I didn't have the latest version, sorry for that. However if i try to run the latest version i get the following error: 

The following WinRM command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mkdir c:\ -force
if ($?) { exit 0 } else { if($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 1 } }

Stdout from the command:



Stderr from the command:

#< CLIXML
<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0
"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"
><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></
PR></MS></Obj><S S="Error">mkdir : The path is not of a legal form._x000D__x000A_</S><S S="Error">At line:1 char:1_x000D
__x000A_</S><S S="Error">+ mkdir c:\ -force_x000D__x000A_</S><S S="Error">+ ~~~~~~~~~~~~~~~~_x000D__x000A_</S><S S="Erro
r">    + CategoryInfo          : InvalidArgument: (C:\:String) [New-Item], Argume _x000D__x000A_</S><S S="Error">   ntEx
ception_x000D__x000A_</S><S S="Error">    + FullyQualifiedErrorId : CreateDirectoryArgumentError,Microsoft.PowerShel _x0
00D__x000A_</S><S S="Error">   l.Commands.NewItemCommand_x000D__x000A_</S><S S="Error"> _x000D__x000A_</S></Objs>

**Comment by mefellows** [comment]
Hi Jonne, no worries at all.

Please see PR #13 for the latest changes, including a couple of bug fixes and the suggestion of yours in this PR to 'unblock' modules in advance.

For better tracking, of your specific problem, I've migrated the defect to issue #14.

For now, I will close this PR whilst we address the issue.

**Pull request closed without merging**
